export const QK = {
  progress: ['progress'] as const,
  notifications: ['notifications'] as const,
  notificationsUnread: ['notifications', 'unread'] as const,
  stats: ['stats'] as const,
  activity: (days: number) => ['activity', days] as const,
  forecast: (days: number) => ['forecast', days] as const,
  leaderboard: ['leaderboard'] as const,
  decks: ['decks'] as const,
  deck: (id: number) => ['decks', id] as const,
  flashcardsRoot: (deckId: number) => ['flashcards', deckId] as const,
  flashcards: (deckId: number, page: number) => ['flashcards', deckId, page] as const,
  flashcard: (id: number) => ['flashcard', id] as const,
  deckDue: (deckId: number) => ['decks', deckId, 'due'] as const,
  courses: ['courses'] as const,
  course: (id: number) => ['courses', id] as const,
  courseRoster: (id: number) => ['courses', id, 'roster'] as const,
  rewards: ['rewards'] as const,
  storeCatalog: ['store', 'catalog'] as const,
  documentStatus: (id: number) => ['document', id, 'status'] as const,
  documentMarkdown: (id: number) => ['document', id, 'markdown'] as const,
  aiJob: (id: number) => ['ai-job', id] as const,
  institution: (id: number) => ['institution', id] as const,
  institutions: ['institutions'] as const,
  adminStats: ['admin', 'stats'] as const,
  adminInstitutionStats: ['admin', 'stats', 'institutions'] as const,
  teacherCourses: ['teacher', 'courses'] as const,
  teacherCourseMetrics: (courseId: number) => ['teacher', 'courses', courseId, 'metrics'] as const,
  teacherWeeklyReport: (courseId: number) => ['teacher', 'courses', courseId, 'weekly-report'] as const,
}
